[project]
name = "fssp"
version = "0.1.0"
description = "Flow-shop scheduling Problem - University project on Algorithm Design and Analysis (ADA)"
authors = [
    {name = "Rômulo Alves de Morais Rocha"},
    {name = "Ryan Silvestre"}
]
license = {text = "MIT License"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy (>=2.3.4,<3.0.0)",
    "jupyter (>=1.1.1,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
